---
- name: install apache
  become: yes
  ansible.builtin.yum:
    name: httpd
    state: present

- name: install git
  become: yes
  become_user: root
  ansible.builtin.yum:
    name: git
    state: present

- name: clone a repo
  become: yes
  become_user: root
  ansible.builtin.git:
    repo: https://github.com/obinnao/tooling.git
    dest: /var/www/html
    force: yes

- name: copy html content to one level up
  become: yes
  become_user: root
  command: cp -r /var/www/html/html/ /var/www/


- name: Start service httpd, if not started
  become: yes
  become_user: root
  ansible.builtin.service:
    name: httpd
    state: started

- name: recursively remove /var/www/html/html/ directory
  become: yes
  become_user: root
  ansible.builtin.file:
    path: /var/www/html/html
    state: absent  
