---

- name: update web, nfs servers
  hosts: webserver , nfs
  remote_user: ec2-user
  become: yes
  become_method: sudo
  become_user: nobody
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

- name: update LB , DB server
  hosts: db , lb
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: nobody
  tasks:
    - name: Update apt repo
      apt:
        update_cache: yes

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest
